subplot(2,1,1)
plot(out.highpressure)
hold on
plot(out.lowpressure)
title('PI Only Model Output')
ylabel('Pressure (psi)')
subplot(2,1,2)
plot(out.valvepos)
ylim([0,90])
ylabel('Handle Position (degrees)')
title('Valve Handle Position')
subplot(2,1,1)
yline(SetPres)
legend('High Pressure Tank Pressure','Set Tank Pressure','Reference Pressure','Location','East')